### ISSUE TITLE
Unable to run trustery add

### ISSUE THREAD

**Issue by SiddharthMalhotra** [musalbas/trustery#5]
I am unable to add an attribute. Please see the error message. What am I missing? 

I have published the contract at Remix (0xd73ca910af172bb194a4f7139cac7c336ebdb7af)

Attribute type: NewAttribute
Attribute identifier: NewIdentifier
Attribute data []: 
Traceback (most recent call last):
  File "/Users/siddharth/anaconda/bin/trustery", line 11, in <module>
    load_entry_point('trustery==0.1', 'console_scripts', 'trustery')()
  File "/Users/siddharth/anaconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/siddharth/anaconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/siddharth/anaconda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/siddharth/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/siddharth/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/siddharth/Desktop/trustery-prototype0.1/pytrustery/trustery/console.py", line 79, in add
    transactions = Transactions()
  File "/Users/siddharth/Desktop/trustery-prototype0.1/pytrustery/trustery/transactions.py", line 26, in __init__
    self.from_address = ethclient.get_accounts()[0]
  File "/Users/siddharth/.local/lib/python2.7/site-packages/eth_client_utils/client.py", line 207, in get_accounts
    response = self.make_request("eth_accounts", [])
  File "/Users/siddharth/.local/lib/python2.7/site-packages/eth_rpc_client/client.py", line 22, in make_request
    data = response.json()
  File "/Users/siddharth/anaconda/lib/python2.7/site-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/siddharth/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/siddharth/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/siddharth/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<img width="1440" alt="screen shot 2018-03-21 at 5 38 49 pm" src="https://user-images.githubusercontent.com/4989369/37697076-d4804c1e-2d2e-11e8-9395-fe330ebbbb28.png">

**Comment by musalbas** [comment]
Did you edit https://github.com/musalbas/trustery/blob/master/pytrustery/trustery/ethapi.py#L12?

**Comment by SiddharthMalhotra** [comment]
Yes, I did edit it. Please check my file attached. Also, attached the
Contract ABI.
You may find contract details here -
https://ropsten.etherscan.io/address/0xd73ca910af172bb194a4f7139cac7c336ebdb7af#code.
<https://ropsten.etherscan.io/address/0xd73ca910af172bb194a4f7139cac7c336ebdb7af#code>
Can I connect with you sometime through TeamViewer? Your help would be
really beneficial, I've been trying to set up the project for more than a
week now :)

Thanks,
Siddharth

**Comment by SiddharthMalhotra** [comment]
[ContractABI.txt](https://github.com/musalbas/trustery/files/1833089/ContractABI.txt)
[ethapi.txt](https://github.com/musalbas/trustery/files/1833085/ethapi.txt)

**Comment by musalbas** [comment]
Not sure then. I would suggest printing the response object received from eth_rpc_client and seeing what the non-JSON response is, this seems to be an issue specific to eth_rpc_client rather than Trustery.

**Comment by musalbas** [comment]
This may be because ethereum-rpc-client - the library Trustery uses to communicate with the local Ethereum node - is deprecated (https://github.com/pipermerriam/ethereum-rpc-client).

**Comment by jaydenzhongyue** [comment]
Hello, sir.
How does the project of your project trustery be deployed?
